import json

corrected = {
    "MLS": "USA - Major League Soccer",
    "אוגנדית ראשונה": "Uganda - Premier League",
    "אוזבקית ראשונה": "Uzbekistan - Super League",
    "אוסטרית ראשונה": "Austria - Bundesliga",
    "אוסטרית שלישית, מזרח": "",
    "אוסטרית שניה": "Austria - 2. Liga",
    "אוסטרלית ראשונה": "Australia - A League",
    "אוקראינית ראשונה": "",
    "אורוגוואית ראשונה": "Uruguay - Primera Division",
    "אזרית ראשונה": "",
    "איחוד האמירויות,ליגה ראשונה": "UAE - Pro League",
    "איטלקית ראשונה": "Italy - Serie A",
    "איטלקית שלישית, בית א'": "",
    "איטלקית שניה": "Italy - Serie B",
    "אינדונזית ראשונה": "Indonesia - Super League",
    "אירית ראשונה": "Ireland - Premier",
    "אישת'מיאן פרמייר ליג": "",
    "אלג'יראית ראשונה": "",
    "אליפות סארנסה, ברזיל": "",
    "אליפות קאריוקה, ברזיל": "",
    "אנגלית מחוזית": "England - National League",
    "אנגלית מחוזית, דרום": "",
    "אנגלית מחוזית, צפון": "",
    "אנגלית ראשונה": "England - League 1",
    "אנגלית שביעית צפון": "",
    "אנגלית שניה": "England - League 2",
    "אקוודורית ראשונה": "Ecuador - Serie A",
    "ארגנטינאית ראשונה": "Argentina - Liga Pro",
    "ארגנטינאית שניה": "Argentina - Primera B Nacional",
    "ארמנית ראשונה": "",
    "אתיופית ראשונה": "",
    "בולגרית ראשונה": "Bulgaria - First League",
    "בולגרית שניה": "",
    "בלגית ראשונה": "Belgium - Pro League",
    "בלגית שניה": "Belgium - Challenger Pro League",
    "ברזילאית ראשונה": "Brazil - Serie A",
    "גביע אוסטרי": "Austria - Amateur Cup",
    "גביע אוקראיני": "",
    "גביע איטלקי": "Italy - Cup",
    "גביע אנגלי": "England - EFL Cup",
    "גביע אסטוני": "Estonia - Cup",
    "גביע בוסניה והרצגובינה": "Bosnia and Herzegovina - Cup",
    "גביע ברזילאי": "Brazil - Cup",
    "גביע ההתאחדות האסייאתית": "AFC - Champions League 2",
    "גביע הולנדי": "",
    "גביע הליגה האיסלנדי": "Iceland - League Cup",
    "גביע טורקי": "",
    "גביע ליברטדורס": "CONMEBOL - Copa Libertadores",
    "גביע ליגות נמוכות": "",
    "גביע סלובני": "Slovenia - Cup",
    "גביע סלובקי": "Slovakia - Cup",
    "גביע ספרדי": "Spain - Copa del Rey",
    "גביע סקוטלנד": "",
    "גביע פורטוגלי": "Portugal - Campeonato de Portugal Prio",
    "גביע צרפתי": "France - Cup",
    "גביע קרואטי": "",
    "גביע רומני": "",
    "גביע רוסי": "",
    "גביע שבדי": "",
    "גיאורגית ראשונה": "Georgia - Erovnuli Liga",
    "גרמנית ראשונה": "Germany - Bundesliga",
    "גרמנית רביעית בוואריה": "",
    "גרמנית רביעית צפון מזרח": "Germany - Regionalliga North East",
    "גרמנית שלישית": "Germany - 3. Liga",
    "גרמנית שניה": "Germany - Bundesliga 2",
    "דנית ראשונה": "Denmark - Superliga",
    "דנית שניה": "Denmark - Division 1",
    "דרום אוסטרליה ראשונה": "Australia - NPL South Australia",
    "דרום אפריקאית ראשונה": "South Africa - PSL",
    "דרום קוריאנית ראשונה": "Korea Republic - K League 1",
    "דרום קוריאנית שניה": "Korea Republic - K League 2",
    "הודית ראשונה": "India - Super League",
    "הולנדית ראשונה": "Netherlands - Eredivisie",
    "הולנדית שניה": "Netherlands - Eerste Divisie",
    "הונגרית ראשונה": "Hungary - NB 1",
    "הונדורס ראשונה, קלאוסורה": "Honduras - Liga Nacional",
    "הליגה האירופית": "UEFA - Europa League",
    "וויילשית ראשונה": "",
    "וולשית שניה דרום": "",
    "ויקטוריה ראשונה": "Australia - NPL Victoria",
    "טוניסאית ראשונה": "",
    "טורקית ראשונה": "Turkey - Super League",
    "טורקית שניה": "Turkey - 1st League",
    "יוונית ראשונה": "Greece - Super League",
    "ירדנית ראשונה": "Jordan - Pro League",
    "ליגה הודית שניה": "India - I-League",
    "ליגה לאומית": "",
    "ליגה לטבית": "",
    "ליגה ליטאית": "Lithuania - A Lyga",
    "ליגה פולנית שנייה": "Poland - 1st Liga",
    "ליגה ראשונה בוסניה והרצגובינה": "",
    "ליגת Winner": "",
    "ליגת האלופות": "UEFA - Champions League",
    "ליגת האלופות האסיאתית": "",
    "ליגת האלופות צפון/מרכז אמריקה": "CONCACAF - Champions Cup",
    "ליגת המפרץ, איחוד האמירויות": "UAE - Pro League",
    "מערב אוסטרליה": "",
    "מצרית ראשונה": "Egypt - Premier League",
    "מקסיקנית ראשונה": "Mexico - Liga MX",
    "מרוקאית ראשונה": "",
    "נורבגית ראשונה": "Norway - Eliteserien",
    "ניו סאות' וויילס ראשונה": "Australia - NPL New South Wales",
    "ניקרגואה ראשונה": "",
    "סוד אמריקנה": "",
    "סופר קאפ דרום אמריקה": "",
    "סופרקאפ סיני": "",
    "סינית ראשונה": "China - Super League",
    "סלובנית ראשונה": "Slovenia - Prva Liga",
    "סלובקית ראשונה": "Slovakia - Super Liga",
    "סעודית ראשונה": "Saudi Arabia - Pro League",
    "סעודית שניה": "Saudi Arabia - Division 1",
    "ספרדית ראשונה": "Spain - La Liga",
    "ספרדית רביעית": "",
    "ספרדית שלישית": "Spain - Primera RFEF Group 2",
    "ספרדית שניה": "Spain - Segunda Division",
    "סקוטית ראשונה": "Scotland - Premiership",
    "סקוטית רביעית": "",
    "סקוטית שלישית": "",
    "סקוטית שניה": "Scotland - Championship",
    "סרבית ראשונה": "",
    "עומאנית ראשונה": "Oman - Pro League",
    "פולנית ראשונה": "Poland - Ekstraklasa",
    "פורטוגלית ראשונה": "Portugal - Primeira Liga",
    "פורטוגלית שניה": "Portugal - Liga 2",
    "פנמית ראשונה, קלאוסורה": "",
    "פרגוואית ראשונה, אפרטורה": "Paraguay - Division Profesional",
    "פרואנית ראשונה": "Peru - Liga 1",
    "פרמייר ליג": "England - Premier League",
    "פרמייר ליג 2, עד 21": "",
    "פרמייר ליג סינגפור": "",
    "צ'ילאנית ראשונה": "Chile - Primera Division",
    "צ'יליאנית שניה": "",
    "צ'כית ראשונה": "Czech Republic - First Liga",
    "צ'כית שניה": "",
    "צ'מפיונשיפ": "England - Championship",
    "צפון אירית ראשונה": "Northern Ireland - Premiership",
    "צפון אירית שניה": "Northern Ireland - Championship",
    "צפון ניו סאות' וויילס ראשונה": "",
    "צרפתית ראשונה": "France - Ligue 1",
    "צרפתית שלישית": "France - National",
    "צרפתית שניה": "France - Ligue 2",
    "קווינסלנד ראשונה": "Australia - NPL Queensland",
    "קולומביאנית ראשונה, אפרטורה": "Colombia - Primera A",
    "קולומביאנית שניה": "Colombia - Primera B",
    "קונפרנס ליג": "UEFA - Conference League",
    "קטארית ראשונה": "Qatar - Stars League",
    "קמרונית ראשונה": "",
    "קנייתית ראשונה": "",
    "קפישאבה ליגה ראשונה": "",
    "קפריסאית ראשונה": "Cyprus - 1st Division",
    "קרואטית ראשונה": "Croatia - HNL",
    "רומנית ראשונה": "Romania - Liga 1",
    "רומנית שניה": "",
    "רוסית ראשונה": "Russia - Premier League",
    "רוסית שניה": "Russia - First League",
    "שוויצרית ראשונה": "Switzerland - Super League",
    "שוויצרית שניה": "Switzerland - Challenge League",
    "תאילנדית ראשונה": "Thailand - League 1",
    "אוסטרלית ראשונה, נשים": "Australia - A League Women",
    "איטלקית שלישית, בית ב'": "",
    "איטלקית שלישית, בית ג'": "",
    "ג'מייקנית ראשונה": "",
    "גביע הליגה המצרי": "",
    "גביע הליגה הפורטוגלי": "",
    "סופר קאפ ספרדי": "",
    "סופרקאפ טורקי": "",
    "סופרקאפ צרפתי": "",
    "כווייתית ראשונה": "",
    "מצרית שניה": "Egypt - 2nd Division A",
    "גביע הסופר ליגה": "",
    "גביע ליגה פינלנד": "",
    "גרמנית רביעית מערב": "",
    "קוסטה ריקנית ראשונה": "Costa Rica - Primera Division",
    "פאוליסטה ליגה ראשונה": "",
    "אליפות גאוצ'ו, ברזיל": ""
}

with open("winner_to_pinnacle_leagues.json", "w", encoding="utf-8") as f:
    json.dump(corrected, f, ensure_ascii=False, indent=4)
print("Saved corrected Pinnacle mapping.")
